[package]
name = "body_count_rn"
version = "0.1.0"
authors = ["snotrz"]

[dependencies]
hyper = "0.9.7"
encoding = "0.2.33"
select = "0.2.2"
postgres = "0.11"
docopt = "0.6"
rustc-serialize = "0.3"

[dependencies.rustless]
git = "https://github.com/rustless/rustless"
